// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kntpoermsnajcuucljwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudHBvZXJtc25hamN1dWNsandlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjczMDAsImV4cCI6MjA2MjgwMzMwMH0.ssAynS_QlCXMSKloRFUe0VFGeV_gJbTQ_sYQ99cXfsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);